"""Alembic migration environment.

The connection URL comes from the application settings (environment variables),
never from alembic.ini, so that credentials stay out of version control.
"""

from logging.config import fileConfig

from sqlalchemy import Connection, engine_from_config, pool, text

from alembic import context
from app.core.config import settings
from app.db.base import Base
from app.models import *  # noqa: F401,F403  (populates Base.metadata)

config = context.config
config.set_main_option("sqlalchemy.url", settings.sqlalchemy_database_uri)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# PostGIS creates these itself; Alembic must not try to manage them.
EXCLUDED_TABLES = {"spatial_ref_sys", "geography_columns", "geometry_columns"}

# The PostGIS image also installs postgis_tiger_geocoder, whose ~34 tables live
# in the `tiger` schema, and postgis_topology, whose tables live in `topology`.
# The tiger install puts its schema on the database search_path, so reflection
# finds those tables as if they were ours and autogenerate proposes dropping
# them. Migrations therefore run with search_path pinned to public.
MIGRATION_SCHEMA = "public"


def _extension_owned_tables(connection: Connection) -> set[str]:
    """Names of tables created by CREATE EXTENSION, which Alembic must not own.

    Asking the catalogue rather than hard-coding a list means a new extension
    never turns into a spurious `drop_table` in an autogenerated revision.
    """
    rows = connection.execute(
        text(
            """
            SELECT c.relname
            FROM pg_class AS c
            JOIN pg_depend AS d
              ON d.objid = c.oid
             AND d.classid = 'pg_class'::regclass
             AND d.deptype = 'e'
            """
        )
    )
    return {row[0] for row in rows}


def make_include_object(extension_tables: frozenset[str] = frozenset()):
    """Build the autogenerate filter, skipping objects we do not manage."""

    def include_object(obj, name, type_, reflected, compare_to) -> bool:
        schema = getattr(obj, "schema", None)
        if schema is not None and schema != MIGRATION_SCHEMA:
            return False
        return not (type_ == "table" and (name in EXCLUDED_TABLES or name in extension_tables))

    return include_object


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting to a database."""
    context.configure(
        url=settings.sqlalchemy_database_uri,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=make_include_object(),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        # Keep extension schemas (tiger, topology) out of reflection, and make
        # the schema new tables land in explicit rather than search_path-order.
        connection.exec_driver_sql(f"SET search_path TO {MIGRATION_SCHEMA}")
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=make_include_object(frozenset(_extension_owned_tables(connection))),
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
